# Translations template for ceilometer.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the ceilometer project.
#
# Translators:
msgid ""
msgstr ""
"Project-Id-Version: Ceilometer\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-06-20 06:01+0000\n"
"PO-Revision-Date: 2014-06-19 20:30+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: French (http://www.transifex.com/projects/p/ceilometer/"
"language/fr/)\n"
"Language: fr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"

#: ceilometer/openstack/common/excutils.py:76
#, python-format
msgid "Original exception being dropped: %s"
msgstr "Exception d'origine en cours de suppression : %s"

#: ceilometer/openstack/common/excutils.py:105
#, python-format
msgid "Unexpected exception occurred %d time(s)... retrying."
msgstr "Exception inattendue survenue %d fois... Nouvel essai."

#: ceilometer/openstack/common/lockutils.py:120
#, python-format
msgid "Could not release the acquired lock `%s`"
msgstr "Impossible de libérer le verrou acquis `%s`"

#: ceilometer/openstack/common/loopingcall.py:89
msgid "in fixed duration looping call"
msgstr "dans l'appel en boucle de durée fixe"

#: ceilometer/openstack/common/loopingcall.py:131
msgid "in dynamic looping call"
msgstr "dans l'appel en boucle dynamique"

#: ceilometer/openstack/common/policy.py:511
#, python-format
msgid "Failed to understand rule %s"
msgstr "Règle %s incompréhensible"

#: ceilometer/openstack/common/policy.py:521
#, python-format
msgid "No handler for matches of kind %s"
msgstr "Aucun gestionnaire pour les correspondances de type %s"

#: ceilometer/openstack/common/policy.py:791
#, python-format
msgid "Failed to understand rule %r"
msgstr "Règle %r incompréhensible"

#: ceilometer/openstack/common/service.py:188
msgid "Exception during rpc cleanup."
msgstr "Exception pendant le nettoyage rpc."

#: ceilometer/openstack/common/service.py:277
msgid "Unhandled exception"
msgstr "Exception non gérée"

#: ceilometer/openstack/common/db/api.py:72
msgid "DB exceeded retry limit."
msgstr "DB dépassé limite de tentatives"

#: ceilometer/openstack/common/db/api.py:76
msgid "DB connection error."
msgstr "erreurs de connexion DB"

#: ceilometer/openstack/common/db/sqlalchemy/session.py:460
msgid "DB exception wrapped."
msgstr "Exception BD encapsulée."

#: ceilometer/openstack/common/db/sqlalchemy/test_migrations.py:267
#, python-format
msgid "Failed to migrate to version %s on engine %s"
msgstr ""

#: ceilometer/openstack/common/middleware/catch_errors.py:40
#, python-format
msgid "An error occurred during processing the request: %s"
msgstr ""
