# Translations template for ceilometer.
# Copyright (C) 2016 ORGANIZATION
# This file is distributed under the same license as the ceilometer project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2016.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: ceilometer 6.0.0.0b3.dev49\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2016-02-08 06:51+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.2.0\n"

#: ceilometer/collector.py:134
#, python-format
msgid "UDP: Cannot decode data sent by %s"
msgstr ""

#: ceilometer/collector.py:141
msgid "UDP: Unable to store meter"
msgstr ""

#: ceilometer/declarative.py:43
#, python-format
msgid "The field 'fields' is required for %s"
msgstr ""

#: ceilometer/declarative.py:56
#, python-format
msgid "Plugin specified, but no plugin name supplied for %s"
msgstr ""

#: ceilometer/declarative.py:65
#, python-format
msgid "No plugin named %(plugin)s available for %(name)s"
msgstr ""

#: ceilometer/declarative.py:91
#, python-format
msgid "Parse error in JSONPath specification '%(jsonpath)s' for %(name)s: %(err)s"
msgstr ""

#: ceilometer/declarative.py:148
#, python-format
msgid ""
"Invalid YAML syntax in Definitions file %(file)s at line: %(line)s, "
"column: %(column)s."
msgstr ""

#: ceilometer/declarative.py:154
#, python-format
msgid "YAML error reading Definitions file %(file)s"
msgstr ""

#: ceilometer/notification.py:206
#, python-format
msgid "Failed to load any notification handlers for %s"
msgstr ""

#: ceilometer/pipeline.py:390
#, python-format
msgid "Unable to load publisher %s"
msgstr ""

#: ceilometer/pipeline.py:428
#, python-format
msgid "Pipeline %(pipeline)s: %(status)s after error from publisher %(pub)s"
msgstr ""

#: ceilometer/pipeline.py:458
#, python-format
msgid ""
"Pipeline %(pipeline)s: Exit after error from transformer %(trans)s for "
"%(smp)s"
msgstr ""

#: ceilometer/pipeline.py:495
#, python-format
msgid "Pipeline %(pipeline)s: Continue after error from publisher %(pub)s"
msgstr ""

#: ceilometer/pipeline.py:511
#, python-format
msgid "Pipeline %(pipeline)s: Error flushing transformer %(trans)s"
msgstr ""

#: ceilometer/agent/manager.py:208
#, python-format
msgid "Prevent pollster %(name)s for polling source %(source)s anymore!"
msgstr ""

#: ceilometer/agent/manager.py:214
#, python-format
msgid "Continue after error from %(name)s: %(error)s"
msgstr ""

#: ceilometer/agent/manager.py:290
#, python-format
msgid "Skip loading extension for %s"
msgstr ""

#: ceilometer/agent/manager.py:293
#, python-format
msgid "Failed to import extension for %(name)s: %(error)s"
msgstr ""

#: ceilometer/agent/manager.py:471
#, python-format
msgid "Unable to discover resources: %s"
msgstr ""

#: ceilometer/agent/manager.py:473
#, python-format
msgid "Unknown discovery extension: %s"
msgstr ""

#: ceilometer/agent/manager.py:482
msgid "Error stopping pollster."
msgstr ""

#: ceilometer/api/middleware.py:102
#, python-format
msgid "Error parsing HTTP response: %s"
msgstr ""

#: ceilometer/api/controllers/v2/base.py:50
#, python-format
msgid "%(entity)s %(id)s Not Found"
msgstr ""

#: ceilometer/api/controllers/v2/base.py:59
#, python-format
msgid "Not Authorized to access %(aspect)s %(id)s"
msgstr ""

#: ceilometer/api/controllers/v2/base.py:220
#, python-format
msgid "Unable to convert the value %(value)s to the expected data type %(type)s."
msgstr ""

#: ceilometer/api/controllers/v2/base.py:225
#, python-format
msgid ""
"The data type %(type)s is not supported. The supported data type list is:"
" %(supported)s"
msgstr ""

#: ceilometer/api/controllers/v2/base.py:230
#, python-format
msgid ""
"Unexpected exception converting %(value)s to the expected data type "
"%(type)s."
msgstr ""

#: ceilometer/api/controllers/v2/events.py:190
#, python-format
msgid ""
"Operator %(operator)s is not supported. The supported operators are: "
"%(supported)s"
msgstr ""

#: ceilometer/api/controllers/v2/events.py:196
#, python-format
msgid ""
"Operator %(operator)s is not supported. Only equality operator is "
"available for field %(field)s"
msgstr ""

#: ceilometer/api/controllers/v2/events.py:303
msgid "Event"
msgstr ""

#: ceilometer/api/controllers/v2/events.py:306
#, python-format
msgid "More than one event with id %s returned from storage driver"
msgstr ""

#: ceilometer/api/controllers/v2/meters.py:308
msgid "Samples should be included in request body"
msgstr ""

#: ceilometer/api/controllers/v2/meters.py:394
msgid "Period must be positive."
msgstr ""

#: ceilometer/api/controllers/v2/meters.py:423
#, python-format
msgid "Invalid period %(period)s: %(err)s"
msgstr ""

#: ceilometer/api/controllers/v2/query.py:203
#, python-format
msgid "Filter expression not valid: %s"
msgstr ""

#: ceilometer/api/controllers/v2/query.py:218
#, python-format
msgid "Order-by expression not valid: %s"
msgstr ""

#: ceilometer/api/controllers/v2/query.py:316
#, python-format
msgid "String %s is not a valid isotime"
msgstr ""

#: ceilometer/api/controllers/v2/query.py:317
#, python-format
msgid "Failed to parse the timestamp value %s"
msgstr ""

#: ceilometer/api/controllers/v2/resources.py:128
msgid "Resource"
msgstr ""

#: ceilometer/api/controllers/v2/root.py:164
msgid "direct option cannot be true when Gnocchi is enabled."
msgstr ""

#: ceilometer/api/controllers/v2/samples.py:144
msgid "Sample"
msgstr ""

#: ceilometer/api/controllers/v2/utils.py:50
msgid "Limit must be positive"
msgstr ""

#: ceilometer/compute/pollsters/cpu.py:56
#, python-format
msgid "could not get CPU time for %(id)s: %(e)s"
msgstr ""

#: ceilometer/compute/pollsters/cpu.py:87
#, python-format
msgid "Could not get CPU Util for %(id)s: %(e)s"
msgstr ""

#: ceilometer/compute/pollsters/disk.py:174
#: ceilometer/compute/pollsters/disk.py:312
#: ceilometer/compute/pollsters/disk.py:447
#: ceilometer/compute/pollsters/disk.py:517
#: ceilometer/compute/pollsters/net.py:110
#, python-format
msgid "Ignoring instance %(name)s: %(error)s"
msgstr ""

#: ceilometer/compute/pollsters/disk.py:645
#, python-format
msgid "Ignoring instance %(name)s (%(instance_id)s) : %(error)s"
msgstr ""

#: ceilometer/compute/pollsters/memory.py:65
#, python-format
msgid "Could not get Memory Usage for %(id)s: %(e)s"
msgstr ""

#: ceilometer/compute/virt/inspector.py:314
#, python-format
msgid "Unable to load the hypervisor inspector: %s"
msgstr ""

#: ceilometer/compute/virt/hyperv/utilsv2.py:221
#, python-format
msgid "VM %s not found on Hyper-V"
msgstr ""

#: ceilometer/compute/virt/hyperv/utilsv2.py:223
#, python-format
msgid "Duplicate VM name found: %s"
msgstr ""

#: ceilometer/compute/virt/libvirt/inspector.py:103
#, python-format
msgid ""
"Error from libvirt while looking up instance <name=%(name)s, id=%(id)s>: "
"[Error Code %(error_code)s] %(ex)s"
msgstr ""

#: ceilometer/compute/virt/libvirt/inspector.py:123
#, python-format
msgid ""
"Failed to inspect data of instance <name=%(name)s, id=%(id)s>, domain "
"state is SHUTOFF."
msgstr ""

#: ceilometer/compute/virt/libvirt/inspector.py:193
#, python-format
msgid ""
"Failed to inspect memory usage of instance <name=%(name)s, id=%(id)s>, "
"can not get info from libvirt."
msgstr ""

#: ceilometer/compute/virt/libvirt/inspector.py:201
#, python-format
msgid ""
"Failed to inspect memory usage of %(instance_uuid)s, can not get info "
"from libvirt: %(error)s"
msgstr ""

#: ceilometer/compute/virt/vmware/inspector.py:106
#: ceilometer/compute/virt/vmware/inspector.py:123
#: ceilometer/compute/virt/vmware/inspector.py:155
#: ceilometer/compute/virt/vmware/inspector.py:168
#, python-format
msgid "VM %s not found in VMware vSphere"
msgstr ""

#: ceilometer/compute/virt/xenapi/inspector.py:53
msgid "XenAPI not installed"
msgstr ""

#: ceilometer/compute/virt/xenapi/inspector.py:59
msgid "Must specify connection_url, and connection_password to use"
msgstr ""

#: ceilometer/compute/virt/xenapi/inspector.py:67
#, python-format
msgid "Could not connect to XenAPI: %s"
msgstr ""

#: ceilometer/compute/virt/xenapi/inspector.py:90
#, python-format
msgid "VM %s not found in XenServer"
msgstr ""

#: ceilometer/compute/virt/xenapi/inspector.py:93
#, python-format
msgid "Multiple VM %s found in XenServer"
msgstr ""

#: ceilometer/compute/virt/xenapi/inspector.py:106
#, python-format
msgid "Could not get VM %s CPU Utilization"
msgstr ""

#: ceilometer/dispatcher/gnocchi.py:60
msgid ""
"The Yaml file that defines mapping between samples and gnocchi "
"resources/metrics"
msgstr ""

#: ceilometer/dispatcher/http.py:76
msgid ""
"Dispatcher target was not set, no meter will be posted. Set the target in"
" the ceilometer.conf file"
msgstr ""

#: ceilometer/dispatcher/http.py:104
#, python-format
msgid "Failed to record metering data: %s"
msgstr ""

#: ceilometer/dispatcher/http.py:107
#, python-format
msgid "message signature invalid, discarding message: %r"
msgstr ""

#: ceilometer/event/converter.py:62
#, python-format
msgid "Invalid trait type '%(type)s' for trait %(trait)s"
msgstr ""

#: ceilometer/event/converter.py:106
#, python-format
msgid "Required field %s not specified"
msgstr ""

#: ceilometer/event/converter.py:283
#, python-format
msgid "Dropping Notification %(type)s (uuid:%(msgid)s)"
msgstr ""

#: ceilometer/hardware/discovery.py:95
#, python-format
msgid "Couldn't obtain IP address of instance %s"
msgstr ""

#: ceilometer/ipmi/platform/intel_node_manager.py:300
msgid "Node Manager init failed"
msgstr ""

#: ceilometer/ipmi/platform/ipmi_sensor.py:101
msgid "Wrong sensor type"
msgstr ""

#: ceilometer/ipmi/platform/ipmitool.py:39
msgid "parse IPMI sensor data failed,unknown sensor type"
msgstr ""

#: ceilometer/ipmi/platform/ipmitool.py:80
msgid "parse IPMI sensor data failed,No data retrieved from given input"
msgstr ""

#: ceilometer/ipmi/platform/ipmitool.py:102
msgid "ipmitool output length mismatch"
msgstr ""

#: ceilometer/ipmi/platform/ipmitool.py:128
msgid "running ipmitool failure"
msgstr ""

#: ceilometer/ipmi/pollsters/node.py:66
#, python-format
msgid "Polling %(name)s failed for %(cnt)s times!"
msgstr ""

#: ceilometer/ipmi/pollsters/node.py:71 ceilometer/ipmi/pollsters/sensor.py:74
#, python-format
msgid "Pollster for %s is disabled!"
msgstr ""

#: ceilometer/ipmi/pollsters/sensor.py:68
#, python-format
msgid "Polling %(mtr)s sensor failed for %(cnt)s times!"
msgstr ""

#: ceilometer/network/services/fwaas.py:48
#, python-format
msgid "Unknown status %(stat)s received on fw %(id)s,skipping sample"
msgstr ""

#: ceilometer/network/services/lbaas.py:63
#, python-format
msgid "Unknown status %(stat)s received on pool %(id)s, skipping sample"
msgstr ""

#: ceilometer/network/services/lbaas.py:111
#, python-format
msgid "Unknown status %(stat)s received on vip %(id)s, skipping sample"
msgstr ""

#: ceilometer/network/services/lbaas.py:152
#, python-format
msgid "Unknown status %(stat)s received on member %(id)s, skipping sample"
msgstr ""

#: ceilometer/network/services/lbaas.py:255
#, python-format
msgid "Ignoring pool %(pool_id)s: %(error)s"
msgstr ""

#: ceilometer/network/services/vpnaas.py:49
#, python-format
msgid "Unknown status %(stat)s received on vpn %(id)s, skipping sample"
msgstr ""

#: ceilometer/network/statistics/opencontrail/client.py:58
#, python-format
msgid "Opencontrail API returned %(status)s %(reason)s"
msgstr ""

#: ceilometer/network/statistics/opendaylight/client.py:232
#: ceilometer/tests/unit/network/statistics/opendaylight/test_client.py:146
#, python-format
msgid "OpenDaylitght API returned %(status)s %(reason)s"
msgstr ""

#: ceilometer/network/statistics/opendaylight/driver.py:169
msgid "Request failed to connect to OpenDaylight with NorthBound REST API"
msgstr ""

#: ceilometer/objectstore/rgw_client.py:48
#, python-format
msgid "RGW AdminOps API returned %(status)s %(reason)s"
msgstr ""

#: ceilometer/publisher/file.py:62
msgid "The path for the file publisher is required"
msgstr ""

#: ceilometer/publisher/file.py:76
msgid "max_bytes and backup_count should be numbers."
msgstr ""

#: ceilometer/publisher/messaging.py:95
#, python-format
msgid "Publishing policy is unknown (%s) force to default"
msgstr ""

#: ceilometer/publisher/messaging.py:147
#, python-format
msgid "Publisher max local_queue length is exceeded, dropping %d oldest samples"
msgstr ""

#: ceilometer/publisher/messaging.py:159
#, python-format
msgid "Failed to publish %d datapoints, queue them"
msgstr ""

#: ceilometer/publisher/messaging.py:163
#, python-format
msgid "Failed to publish %d datapoints, dropping them"
msgstr ""

#: ceilometer/publisher/udp.py:67
msgid "Unable to send sample over UDP"
msgstr ""

#: ceilometer/storage/impl_sqlalchemy.py:310
#, python-format
msgid "Unknown metadata type. Key (%s) will not be queryable."
msgstr ""

#: ceilometer/storage/hbase/utils.py:474
#, python-format
msgid "Cannot create table %(table_name)s   it already exists. Ignoring error"
msgstr ""

#: ceilometer/storage/mongo/utils.py:269
#, python-format
msgid "Unable to connect to the database server: %(errmsg)s."
msgstr ""

#: ceilometer/storage/mongo/utils.py:411
#, python-format
msgid ""
"Unable to reconnect to the primary mongodb after %(retries)d retries. "
"Giving up."
msgstr ""

#: ceilometer/storage/mongo/utils.py:415
#, python-format
msgid ""
"Unable to reconnect to the primary mongodb: %(errmsg)s. Trying again in "
"%(retry_interval)d seconds."
msgstr ""

#: ceilometer/transformer/arithmetic.py:57
#, python-format
msgid "Arithmetic transformer must use at least one meter in expression '%s'"
msgstr ""

#: ceilometer/transformer/arithmetic.py:79
msgid "Expression evaluated to a NaN value!"
msgstr ""

#: ceilometer/transformer/arithmetic.py:95
#, python-format
msgid "Unable to evaluate expression %(expr)s: %(exc)s"
msgstr ""

#: ceilometer/transformer/conversions.py:198
#, python-format
msgid "dropping out of time order sample: %s"
msgstr ""

#: ceilometer/transformer/conversions.py:216
#, python-format
msgid "dropping sample with no predecessor: %s"
msgstr ""

